services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: ci-db-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - database-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ci-backend-container
    environment:
      POSTGRES_DB_HOST: ci-db-container
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: pet_store
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      FRONTEND_URL: http://localhost:${FRONTEND_APP_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - database
    networks:
      - app-network
      - database-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ci-frontend-container
    environment:
      VITE_API_BASE_URL: http://localhost:${SERVER_PORT}/api
    ports:
      - ${FRONTEND_APP_PORT}:5173
    networks:
      - app-network
    depends_on:
      - database
      - backend

volumes:
  postgres:

networks:
  app-network:
    driver: bridge
  database-network:
    driver: bridge
    internal: true
