version: "3.8"

services:
  database:
    image: postgres:17-alpine
    container_name: ci-db-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data
    networks:
      - database-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ci-backend-container
    environment:
      POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:8080
    depends_on:
      - database
    networks:
      - app-network
      - database-network

volumes:
  postgres:

networks:
  app-network:
    driver: bridge
  database-network:
    driver: bridge
    internal: true
